name: flutter_amazon_clone
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloudinary_public: ^0.23.1
  connectivity_plus: ^6.1.0
  dotted_border: ^2.1.0
  file_picker: ^8.1.2
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.6.1
  http: ^1.2.2
  intl: ^0.19.0
  pay: ^2.0.0
  provider: ^6.1.2
  rename_app: ^1.6.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/
    - assets/gpay.json
